name: Docker Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set env
        run: echo "REPOSITORY_NAME=${{ github.event.repository.name }}" | sed 's/docker-image-//' >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set tag to build
        run: |
          tag=${{github.ref}}
          if [[ $tag == 'refs/tags/'* ]]; then
              tag=$(echo $tag | sed -e 's/refs\/tags\///')
          else if [[ $tag == 'refs/heads/main' ]]; then
              tag=latest
          fi
          echo "TAG=$tag" >> $GITHUB_ENV
      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64, linux/arm64
          target: prod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{env.REPOSITORY_NAME}}:${{env.TAG}}
